# Default values for welearn-back.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: localhost:5000
  repository: welearn-back_web
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

### PostgreSQL custom values
postgresql:
  postgresqlDatabase: welearn
  postgresqlPassword: secret
  postgresqlUsername: postgres
  initdbScripts:
    init_postgresql.sh: |
      echo "Creating database 'welearn-test' owned by user 'postgres'
      echo "CREATE DATABASE welearn-test OWNER postgres;" | psql -v ON_ERROR_STOP=1 --username postgres -d welearn-test
      
### Redis custom values
redis:
  cluster.enable: false

### ES custom values

service:
  type: ClusterIP
  port: 3000 

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
